// Generated by CoffeeScript 1.7.1
var Thermostat;

Thermostat = (function() {
  function Thermostat() {}

  Thermostat.prototype.temperature = 20;

  Thermostat.prototype.minimumTemperature = 10;

  Thermostat.prototype.powerSavingMode = true;

  Thermostat.prototype.maximumTemperature = function() {
    if (this.powerSavingMode) {
      return 25;
    } else {
      return 32;
    }
  };

  Thermostat.prototype.warmer = function() {
    if (this.temperature < this.maximumTemperature()) {
      return this.temperature += 1;
    }
  };

  Thermostat.prototype.cooler = function() {
    if (this.temperature > this.minimumTemperature) {
      return this.temperature -= 1;
    }
  };

  Thermostat.prototype.reset = function() {
    return this.temperature = 20;
  };

  Thermostat.prototype.energyUsage = function() {
    if (this.temperature >= 25) {
      return 'high';
    }
    if (this.temperature >= 18) {
      return 'medium';
    }
    return 'low';
  };

  return Thermostat;

})();
